services:
  - type: web
    name: fiskeat-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SODEXO_API_KEY
        sync: false
      - key: SODEXO_LOCATION_ID
        value: "73110001"
      - key: SODEXO_SITE_ID
        value: "22135"
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "5001"
      - key: FLASK_ENV
        value: "production"

